[general]
shuffle_caption = false
caption_extension = '.txt'
keep_tokens = 1

[[datasets]]
resolution = 1024
batch_size = 1
enable_bucket = true
bucket_reso_steps = 32

[[datasets.subsets]]
image_dir = '/workspace/train_data/20_oilpstyle'
num_repeats = 10
